@FilmVault_HostAddress = http://localhost:5041

### Get all movies
GET {{FilmVault_HostAddress}}/movie
Accept: application/json

###

### Get movie by ID
GET {{FilmVault_HostAddress}}/movie/1
Accept: application/json

###

### Create a new movie
POST {{FilmVault_HostAddress}}/movie
Content-Type: application/json

{
  "title": "The Matrix",
  "director": {
    "name": "Lana Wachowski",
    "isAwardWinner": true
  },
  "genres": [
    {
      "name": "Action"
    },
    {
      "name": "Sci-Fi"
    }
  ],
  "isAvailableIn4K": true
}


###

### Add genre to a movie
PUT {{FilmVault_HostAddress}}/movie/1/addGenre?genreId=3
Accept: application/json

###

### Update director of a movie
PUT {{FilmVault_HostAddress}}/movie/1/updateDirector?directorId=2
Accept: application/json

###

### Delete a movie
DELETE {{FilmVault_HostAddress}}/movie/1
Accept: application/json

###
